// pie_chart.dart

import 'package:flutter/material.dart';
import 'package:expense_tracker/models/expense.dart';

class PieChartUtils {
  
  // Function to get color for each category
  static Color getCategoryColor(Category category) {
     String categoryName = category.toString().split('.').last.toUpperCase();
    
    switch (category) {
      case Category.food:
        return Colors.blue;
      case Category.travel:
        return Colors.green;
      case Category.leisure:
        return Colors.red;
      case Category.work:
        return Colors.orange;
      case Category.groceries:
        return Colors.purple;
      case Category.internet:
        return Colors.yellow;
      case Category.gas:
        return Colors.teal;
      case Category.investment:
        return Colors.cyan;
      case Category.clothing:
        return Colors.brown;
      case Category.mobile:
        return Colors.pink;
      case Category.entertainment:
        return Colors.indigo;
      case Category.education:
        return Colors.amber;
      case Category.personal_care:
        return Colors.lime;
      case Category.health:
        return Colors.redAccent;
      case Category.fitness:
        return Colors.greenAccent;
      case Category.kids:
        return Colors.purpleAccent;
      case Category.gifts_and_donations:
        return Colors.orangeAccent;
      case Category.bills_and_utilities:
        return Colors.tealAccent;
      case Category.auto:
        return Colors.cyanAccent;
      case Category.taxes:
        return Colors.brown;
      case Category.pet_care:
        return Colors.pinkAccent;
      case Category.savings:
        return Colors.indigoAccent;
      case Category.misc:
        return Colors.amberAccent;
      case Category.household:
        return Colors.limeAccent;
      case Category.air_tickets:
        return Colors.redAccent;
      case Category.beauty:
        return Colors.greenAccent;
      case Category.bike:
        return Colors.purpleAccent;
      case Category.books:
        return Colors.orangeAccent;
      case Category.bus_fare:
        return Colors.tealAccent;
      case Category.cable:
        return Colors.cyanAccent;
      case Category.cake:
        return Colors.brown;
      case Category.car:
        return Colors.pinkAccent;
      case Category.cc_bill_payment:
        return Colors.indigoAccent;
      case Category.cigarette:
        return Colors.amberAccent;
      case Category.coffee:
        return Colors.limeAccent;
      case Category.drinks:
        return Colors.redAccent;
      case Category.electricity:
        return Colors.greenAccent;
      case Category.electronics:
        return Colors.purpleAccent;
      case Category.finance:
        return Colors.orangeAccent;
      case Category.flowers:
        return Colors.tealAccent;
      case Category.fruits:
        return Colors.cyanAccent;
      case Category.vegetables:
        return Colors.brown;
      case Category.games:
        return Colors.pinkAccent;
      case Category.hotel:
        return Colors.indigoAccent;
      case Category.ice_cream:
        return Colors.amberAccent;
      case Category.maid:
        return Colors.limeAccent;
      case Category.driver:
        return Colors.redAccent;
      case Category.maintenance:
        return Colors.greenAccent;
      case Category.medicines:
        return Colors.purpleAccent;
      case Category.milk:
        return Colors.orangeAccent;
      case Category.movie:
        return Colors.tealAccent;
      case Category.fuel:
        return Colors.cyanAccent;
      case Category.pizza:
        return Colors.brown;
      case Category.printing_and_scanning:
        return Colors.pinkAccent;
      case Category.rent:
        return Colors.indigoAccent;
      case Category.salon:
        return Colors.amberAccent;
      case Category.shopping:
        return Colors.limeAccent;
      case Category.stationery:
        return Colors.redAccent;
      case Category.taxi:
        return Colors.greenAccent;
      case Category.toys:
        return Colors.purpleAccent;
      case Category.train:
        return Colors.orangeAccent;
      case Category.vacation:
        return Colors.tealAccent;
      case Category.water:
        return Colors.cyanAccent;
      case Category.home_loan:
        return Colors.brown;
      case Category.personal_loan:
        return Colors.pinkAccent;
      case Category.education_loan:
        return Colors.indigoAccent;
      case Category.festivals:
        return Colors.amberAccent;
      case Category.car_loan:
        return Colors.limeAccent;
      case Category.laundry:
        return Colors.redAccent;
      case Category.emi:
        return Colors.greenAccent;
      case Category.atm:
        return Colors.purpleAccent;
      case Category.toll:
        return Colors.orangeAccent;
      case Category.bonus:
        return Colors.tealAccent;
      case Category.interest_income:
        return Colors.cyanAccent;
      case Category.reimbursement:
        return Colors.brown;
      case Category.rental_income:
        return Colors.pinkAccent;
      case Category.returned_purchase:
        return Colors.indigoAccent;
      case Category.salary:
        return Colors.amberAccent;
      default:
        return Colors.grey;
    }
  }
}
